{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "ProgrammingExcercise",
    "description" : "An Example Program.",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/JURRANDSUMMERVILLE08/ProgrammingExcercise/1.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}